name: Node.js Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hmk20000'
      
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      
      - run: npm ci
      - run: npm run build
      
      - name: Check if version has been updated
        id: check
        run: |
          current_version=$(npm pkg get version | tr -d '"')
          git fetch origin
          previous_version=$(git show origin/main:package.json | grep version | cut -d'"' -f4)
          if [ "$current_version" = "$previous_version" ]; then
            echo "version_changed=false" >> $GITHUB_OUTPUT
          else
            echo "version_changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Bump version
        if: steps.check.outputs.version_changed == 'false'
        run: |
          npm version patch
          git push
          git push --tags
      
      - name: Push changes if version was manually updated
        if: steps.check.outputs.version_changed == 'true'
        run: |
          git push
          git push --tags
      
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
